### ISSUE TITLE
img en inhoud tegen elkaar aan

### ISSUE THREAD

**Issue by Theo-denBlanken** [pimhakkert/modal_screen#1]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
.album {
  display: grid;
  grid-template-columns: 1fr 1fr;
  max-width: 80%;
} 
```

URL: https://github.com/pimhakkert/modal_screen/blob/master/style.css

Feedback: geef ze wat tussenruimte[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"558b740ec6d1c0448b2fe2927e10353fa5d5b909","path":"style.css","reviewer":"Theo-denBlanken"}')

**Comment by pimhakkert** [comment]
Fixed
