### ISSUE TITLE
in combinatie met grid-def

### ISSUE THREAD

**Issue by Theo-denBlanken** [pimhakkert/modal_screen#2]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
.album img {
  max-width: 100%;
} 
```

URL: https://github.com/pimhakkert/modal_screen/blob/master/style.css

Feedback: geeft het een vreemde schurende lay-out[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"558b740ec6d1c0448b2fe2927e10353fa5d5b909","path":"style.css","reviewer":"Theo-denBlanken"}')

**Comment by pimhakkert** [comment]
Fixed
