### ISSUE TITLE
sluitknop kan beter gestyled worden

### ISSUE THREAD

**Issue by Theo-denBlanken** [pimhakkert/modal_screen#3]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/pimhakkert/modal_screen/blob/master/style.css

Feedback: positie, grootte, hover enz[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"558b740ec6d1c0448b2fe2927e10353fa5d5b909","path":"style.css","reviewer":"Theo-denBlanken"}')

**Comment by pimhakkert** [comment]
Fixed
